# Import Libraries

In [1]:
import pandas as pd

# Load Source Data

In [5]:
src_games = pd.read_csv('../data/source_data/games.csv')
src_turns = pd.read_csv('../data/source_data/turns.csv')
src_train = pd.read_csv('../data/source_data/train.csv')
src_test = pd.read_csv('../data/source_data/test.csv')

# Load Data With Rack Usage Feature

In [6]:
prc_games = pd.read_csv('../data/preprocessed_data/new_games.csv')
prc_turns = pd.read_csv('../data/preprocessed_data/new_turns.csv')
prc_train = pd.read_csv('../data/preprocessed_data/new_train.csv')
prc_test = pd.read_csv('../data/preprocessed_data/new_test.csv')

# Load Cleaned Data

In [8]:
cleaned_train = pd.read_csv('../data/cleaned_data/cleaned_train.csv')
cleaned_test = pd.read_csv('../data/cleaned_data/cleaned_test.csv')

# Split datasets to users_dataset and bots_dataset on train only

In [18]:
bots = ['BetterBot', 'STEEBot', 'HastyBot']

In [19]:
user_df = src_train[~src_train["nickname"].isin(bots)] 
user_df = user_df.rename(
    columns={"nickname": "user_name", "score": "user_score", "rating": "user_rating"}
) 

bot_df = src_train[src_train["nickname"].isin(bots)]

bot_df = bot_df.rename(
    columns={"nickname": "bot_name", "score": "bot_score", "rating": "bot_rating"}
)

# Some Analyses and Test

In [14]:
prc_turns.head()

,game_id,turn_number,nickname,rack,location,move,points,score,turn_type,rack_len,rack_usage
0,1,1,BetterBot,DDEGITT,8G,DIG,10,10,Play,7.0,0.428571
1,1,2,stevy,AEHOPUX,7H,HAP,18,18,Play,7.0,0.428571
2,1,3,BetterBot,DEELTTU,6I,LUTE,16,26,Play,7.0,0.571429
3,1,4,stevy,EMORSUX,5K,UM,16,34,Play,7.0,0.285714
4,1,5,BetterBot,ACDEITU,L5,..DICATE,28,54,Play,7.0,0.857143

In [15]:
prc_games.head()

,game_id,first,time_control_name,game_end_reason,winner,created_at,lexicon,initial_time_seconds,increment_seconds,rating_mode,max_overtime_minutes,game_duration_seconds,bot_nickname,bot_rating,bot_id
0,1,BetterBot,regular,STANDARD,1,08/26/2022 3:38,NWL20,1200,0,CASUAL,1,674.844274,BetterBot,1637.0,1.0
1,2,Super,regular,STANDARD,1,08/10/2022 19:19,CSW21,3600,0,RATED,1,364.214418,BetterBot,2000.0,1.0
2,3,BetterBot,regular,STANDARD,1,09/04/2022 8:04,CSW21,900,0,RATED,5,492.268262,BetterBot,2071.0,1.0
3,4,BetterBot,regular,RESIGNED,0,09/12/2022 2:36,CSW21,3600,0,CASUAL,1,350.861141,BetterBot,1936.0,1.0
4,5,STEEBot,regular,STANDARD,0,09/06/2022 4:31,NWL20,1200,0,CASUAL,1,642.688722,STEEBot,1844.0,2.0

In [20]:
prc_train.head()

   game_id        nickname  score  mean_rack_usage  rating
0        1       BetterBot    335         0.596154    1637
1        1           stevy    429         0.457143    1500
2        3       davidavid    440         0.469388    1811
3        3       BetterBot    318         0.538462    2071
4        4  Inandoutworker    119         0.285714    1473

In [21]:
prc_turns.head()

,game_id,turn_number,nickname,rack,location,move,points,score,turn_type,rack_len,rack_usage
0,1,1,BetterBot,DDEGITT,8G,DIG,10,10,Play,7.0,0.428571
1,1,2,stevy,AEHOPUX,7H,HAP,18,18,Play,7.0,0.428571
2,1,3,BetterBot,DEELTTU,6I,LUTE,16,26,Play,7.0,0.571429
3,1,4,stevy,EMORSUX,5K,UM,16,34,Play,7.0,0.285714
4,1,5,BetterBot,ACDEITU,L5,..DICATE,28,54,Play,7.0,0.857143

In [22]:
prc_games.head()

,game_id,first,time_control_name,game_end_reason,winner,created_at,lexicon,initial_time_seconds,increment_seconds,rating_mode,max_overtime_minutes,game_duration_seconds,bot_nickname,bot_rating,bot_id
0,1,BetterBot,regular,STANDARD,1,08/26/2022 3:38,NWL20,1200,0,CASUAL,1,674.844274,BetterBot,1637.0,1.0
1,2,Super,regular,STANDARD,1,08/10/2022 19:19,CSW21,3600,0,RATED,1,364.214418,BetterBot,2000.0,1.0
2,3,BetterBot,regular,STANDARD,1,09/04/2022 8:04,CSW21,900,0,RATED,5,492.268262,BetterBot,2071.0,1.0
3,4,BetterBot,regular,RESIGNED,0,09/12/2022 2:36,CSW21,3600,0,CASUAL,1,350.861141,BetterBot,1936.0,1.0
4,5,STEEBot,regular,STANDARD,0,09/06/2022 4:31,NWL20,1200,0,CASUAL,1,642.688722,STEEBot,1844.0,2.0